application: richmine-server-app
module: richmine-server-module
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: B8
manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: master_app.application